### ISSUE TITLE
不能正确处理使用ports源的Ubuntu系统

### ISSUE THREAD

**Issue by JonathanHouten** [tuna/oh-my-tuna#14]
Ports源，服务于运行于arm64, armhf这些架构上的Ubuntu，不能与常规源混用，否则会在update时获取到错误的软件列表，使得upgrade和install始终提示找不到软件。
在oh my tuna 中，并没有相关检查，导致oh my tuna会在未提示状态下直接将常规源作为sources.list，即无视其运行在需要使用ports源的环境中
考虑到tunaMirrors有ubuntu-ports镜像，建议考虑加入对Ports源的支持。

======
附1：这种环境常见于树莓派，香橙派(本人在此遇到了这个问题)，以及任何名字中含有派的非食品设备中

======
附2：默认源设置
deb http://ports.ubuntu.com/ubuntu-ports/ xenial main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-backports main restricted universe multiverse

**Comment by JonathanHouten** [comment]
附3：我的字为什么会这么大

**Comment by jiegec** [comment]
Markdown 语法了解一下。我帮你改了。

**Comment by ZenithalHourlyRate** [comment]
#32 
Ubuntu 支持已经实现
