### ISSUE TITLE
debian 没有修改 源

### ISSUE THREAD

**Issue by vmvz** [tuna/oh-my-tuna#15]
执行后,还是163的源 

请看图
![image](https://user-images.githubusercontent.com/1652700/40212075-afa05f36-5a80-11e8-9403-b44a8355633c.png)

**Comment by jiegec** [comment]
上面没有显示 activating debian。自然是没有更改你的sources.list. 因为你已经自定义了源，可能添加了其它第三方源，oh-my-tuna 判断目前不是默认源的话，会选择跳过。

**Comment by vmvz** [comment]
@jiegec 如果已经是第三方源,可以考虑给个提示, 是否替换, 让用户自己选择, 体验会更好.

谢谢
