### ISSUE TITLE
tuna.moe 打不开

### ISSUE THREAD

**Issue by VMatrix1900** [tuna/oh-my-tuna#18]
Chrome 67 返回：
```
tuna.moe 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

`wget` 以及 `curl` 均返回 SSLv3 alert handshake 无法下载。

似乎是因为 tuna.moe 的TLS版本太低？

**Comment by Harry-Chen** [comment]
您好，感谢反馈。我们注意到了这个问题，一旦查明原因将立刻进行修复。

**Comment by huangbiubiu** [comment]
用`wget`返回404：
```
wget https://tuna.moe/oh-my-tuna/oh-my-tuna.py
--2018-09-24 19:04:40--  https://tuna.moe/oh-my-tuna/oh-my-tuna.py
Resolving tuna.moe (tuna.moe)... 2001:da8:20f:4430::27, 202.204.128.161
Connecting to tuna.moe (tuna.moe)|2001:da8:20f:4430::27|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-09-24 19:04:40 ERROR 404: Not Found.
```

**Comment by xavieryao** [comment]
<https://raw.githubusercontent.com/tuna/oh-my-tuna/master/oh-my-tuna.py><https://raw.githubusercontent.com/tuna/oh-my-tuna/master/oh-my-tuna.py><https://raw.githubusercontent.com/tuna/oh-my-tuna/master/oh-my-tuna.py>https://raw.githubusercontent.com/tuna/oh-my-tuna/master/oh-my-tuna.py
<https://raw.githubusercontent.com/tuna/oh-my-tuna/master/oh-my-tuna.py>
On Sep 25, 2018, at 10:05 AM, Huang Yuheng <notifications@github.com> wrote:


用wget返回404：

wget https://tuna.moe/oh-my-tuna/oh-my-tuna.py
--2018-09-24 19:04:40--  https://tuna.moe/oh-my-tuna/oh-my-tuna.py
Resolving tuna.moe (tuna.moe)... 2001:da8:20f:4430::27, 202.204.128.161
Connecting to tuna.moe (tuna.moe)|2001:da8:20f:4430::27|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-09-24 19:04:40 ERROR 404: Not Found.
