### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by VMatrix1900** [tuna/oh-my-tuna#19]
Ubuntu 18.04 已经不带python 2了。请提供python 3 可用的版本

**Comment by xavieryao** [comment]
是 python 2/3 兼容的

On Jul 1, 2018, at 6:43 PM, Vincent Stone <notifications@github.com<mailto:notifications@github.com>> wrote:


Ubuntu 18.04 已经不带python 2了。请提供python 3 可用的版本

**Comment by xavieryao** [comment]
@VMatrix1900 我先 close 了，如果发现有 Python3 不兼容的地方请再跟进。
