### ISSUE TITLE
Ubuntu 20.04 的docker内无法使用

### ISSUE THREAD

**Issue by kaiwu-astro** [tuna/oh-my-tuna#38]
在ubuntu 20.04的docker里使用：

`python3 oh-my-tuna.py --global`，选择a

查看/etc/apt/sources.list发现每一行里面的ubuntu版本都是None，例如
`deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ None main restricted universe multiverse`

就必须得手动修改，请问能适用于docker环境吗？谢谢

**Comment by shankerwangmiao** [comment]
应该是由于 docker 环境中没有 lsb_release 这个命令导致的。

https://github.com/tuna/oh-my-tuna/blob/acc0b997d0892cebd9d535d04cdc9ac35636fa9c/oh-my-tuna.py#L567


另外，by design，oh-my-tuna 应该意图是给用户交互式使用的，在 docker 环境中自动地使用 oh-my-tuna 可能会发生一些意料之外的问题。

**Comment by kaiwu-astro** [comment]
好的👌，感谢回复
