### ISSUE TITLE
Support Debian

### ISSUE THREAD

**Issue by xavieryao** [tuna/oh-my-tuna#4]
Should be similar to Ubuntu

**Comment by Harry-Chen** [comment]
稍等，Debian 还有 debian-security

**Comment by CircuitCoder** [comment]
嗯...我们怎么处理source.list.d里面的东西啊？
是遍历一遍把所有可以替换的都替掉吗

**Comment by CircuitCoder** [comment]
现在的处理方式：只更新sources.list，不管sources.list.d
